---

- name: Check the installed version of Kimai
  block:

    - name: "Stat {{ kimai_wwwroot }}/bin/console"
      ansible.builtin.stat:
        path: "{{ kimai_wwwroot }}/bin/console"
      register: kimai_console


    - name: Check the verson of Kimai when the console is present
      when: kimai_console.stat.exists | bool
      block:

        - name: Check which version of Kimai is installed
          ansible.builtin.command: bin/console --no-ansi -n kimai:version --short
          args:
            chdir: "{{ kimai_wwwroot }}"
          check_mode: false
          changed_when: false
          register: kimai_install_check
          failed_when: kimai_install_check.rc is not regex('^0$|^1$|^127$')
          become: true
          become_user: "{{ kimai_user }}"

        - name: Set a variable for the installed version of Kimai
          ansible.builtin.set_fact:
            kimai_installed: "{{ kimai_install_check.stdout | trim }}"
          when: ( kimai_install_check is defined ) and ( kimai_install_check.rc == 0 )
    # END OF BLOCK
  # END OF BLOCK
